language: c
sudo: required
dist: trusty

stages:
  - build Release
  
jobs:
  include:

    # LINUX BUILD
    - stage: build Release
      if: branch != coverity_scan
      name: "Linux Build Release"
      os: linux
      before_install:
        - mkdir paho.mqtt.c
        - wget https://github.com/eclipse/paho.mqtt.c/releases/download/v1.3.2/Eclipse-Paho-MQTT-C-1.3.2-Linux.tar.gz 
        - tar xvf Eclipse-Paho-MQTT-C-1.3.2-Linux.tar.gz -C ./paho.mqtt.c --strip-components=1
        - export PAHO_HOME=$TRAVIS_BUILD_DIR/paho.mqtt.c
      install:
        - mkdir cmake && cd cmake && cmake ..
      script:
        - make install VERBOSE=1
      before_deploy:
        - tar -zcvf mqtt-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz mqtt
      deploy:
        provider: releases
        api_key:
          secure: cNdATvJmeCHIyoxVf6Hx6YWknl4Zk1880dke/8MvrL+eKfdGMLYliEfqGIwIpWUVbUv0E7F0kgOJH+wJm0VeHBSbhYVXaGP6+FSRA0q9on87/PHD2aJANbNu+ayJZGBRA7HJwv3Gi9cyQQPJyFt4lz5XqDmuA7WihM69nekvlnU/JjDDaoCidYvhzxkTvRqji7CsnqFkJvJNLrw9YbZf7CB/yBRBEKGgEV0bHQ4dSxIpAoTILziUgI3ys0RSIOJ9y+f1zNZyTyUpxhfvkogxcOT+9N/jbxwix93mF/IuZ1Crymsbt4SgXpeDZtj73Nf++eSMspnZQi7DvMTu5oLEGRrbb60XMOE3Ih9NiidOpcRC8uMPchb1ZAT8xrswtTlD3SX97de70UJbdNnU4AbRnBSb7D/ah5kZxz4L+U9RhuADlmGTooRx5rLMI9BSnU65Ibxct5DcE4cgyxOAipiYOmIL2uuk/XFeZXXpumCcObX3tKmZCZSS+a3A/Uwwy4MdBRzFhMiSYnfNgcysw7br3gRUqlrc0k4TW+gneHpI3cpyV0/BQGgQkAVfRzlXC0wEAhwllRK6f48nt8PH+Bhd8JFtS/Sq9RsDr4IIstqKPNvWl/xv+6SlaFMYEd5/qRGyU/Z0ViUZVjgecQ0REcNIq837ZSywOj5YXXI8EWtRfpk=
        file: mqtt-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz
        on:
          tags: true
        skip_cleanup: 'true'

    # OSX BUILD
    - stage: build Release
      if: branch != coverity_scan
      name: "MacOS Build Release"
      os: osx
      before_install:
        - mkdir paho.mqtt.c
        - wget https://github.com/eclipse/paho.mqtt.c/releases/download/v1.3.2/Eclipse-Paho-MQTT-C-1.3.2-Darwin.tar.gz
        - tar xvf Eclipse-Paho-MQTT-C-1.3.2-Darwin.tar.gz -C ./paho.mqtt.c --strip-components=1
        - export PAHO_HOME=$TRAVIS_BUILD_DIR/paho.mqtt.c      
      install:
        - mkdir cmake && cd cmake && cmake ..
      script:
        - make install VERBOSE=1
      before_deploy:
        - tar -zcvf mqtt-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz mqtt
      deploy:
        provider: releases
        api_key:
          secure: cNdATvJmeCHIyoxVf6Hx6YWknl4Zk1880dke/8MvrL+eKfdGMLYliEfqGIwIpWUVbUv0E7F0kgOJH+wJm0VeHBSbhYVXaGP6+FSRA0q9on87/PHD2aJANbNu+ayJZGBRA7HJwv3Gi9cyQQPJyFt4lz5XqDmuA7WihM69nekvlnU/JjDDaoCidYvhzxkTvRqji7CsnqFkJvJNLrw9YbZf7CB/yBRBEKGgEV0bHQ4dSxIpAoTILziUgI3ys0RSIOJ9y+f1zNZyTyUpxhfvkogxcOT+9N/jbxwix93mF/IuZ1Crymsbt4SgXpeDZtj73Nf++eSMspnZQi7DvMTu5oLEGRrbb60XMOE3Ih9NiidOpcRC8uMPchb1ZAT8xrswtTlD3SX97de70UJbdNnU4AbRnBSb7D/ah5kZxz4L+U9RhuADlmGTooRx5rLMI9BSnU65Ibxct5DcE4cgyxOAipiYOmIL2uuk/XFeZXXpumCcObX3tKmZCZSS+a3A/Uwwy4MdBRzFhMiSYnfNgcysw7br3gRUqlrc0k4TW+gneHpI3cpyV0/BQGgQkAVfRzlXC0wEAhwllRK6f48nt8PH+Bhd8JFtS/Sq9RsDr4IIstqKPNvWl/xv+6SlaFMYEd5/qRGyU/Z0ViUZVjgecQ0REcNIq837ZSywOj5YXXI8EWtRfpk=
        file: mqtt-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz
        on:
          tags: true
        skip_cleanup: 'true'

    # WINDOWS (VISUAL STUDIO 2017) BUILD
    - stage: build Release
      if: branch != coverity_scan
      name: "Windows MVS 2017 Build Release"
      os: windows
      before_install:
        - mkdir paho.mqtt.c
        - wget https://github.com/eclipse/paho.mqtt.c/releases/download/v1.3.2/eclipse-paho-mqtt-c-win64-1.3.2.zip
        - 7z x -opaho.mqtt.c eclipse-paho-mqtt-c-win64-1.3.2.zip
        - export PAHO_HOME=$TRAVIS_BUILD_DIR/paho.mqtt.c   
      install:
        - mkdir cmake && cd cmake && cmake -G "Visual Studio 15 2017 Win64" ..
      script:
        - export MSBUILD_PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin/"
        - export PATH=$PATH:$MSBUILD_PATH
        - MSBuild.exe INSTALL.vcxproj //m //nologo //verbosity:normal //p:Configuration=Release //p:Platform=x64
      before_deploy:
        - 7z a -r mqtt-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.zip mqtt/*
      deploy:
        provider: releases
        api_key:
          secure: cNdATvJmeCHIyoxVf6Hx6YWknl4Zk1880dke/8MvrL+eKfdGMLYliEfqGIwIpWUVbUv0E7F0kgOJH+wJm0VeHBSbhYVXaGP6+FSRA0q9on87/PHD2aJANbNu+ayJZGBRA7HJwv3Gi9cyQQPJyFt4lz5XqDmuA7WihM69nekvlnU/JjDDaoCidYvhzxkTvRqji7CsnqFkJvJNLrw9YbZf7CB/yBRBEKGgEV0bHQ4dSxIpAoTILziUgI3ys0RSIOJ9y+f1zNZyTyUpxhfvkogxcOT+9N/jbxwix93mF/IuZ1Crymsbt4SgXpeDZtj73Nf++eSMspnZQi7DvMTu5oLEGRrbb60XMOE3Ih9NiidOpcRC8uMPchb1ZAT8xrswtTlD3SX97de70UJbdNnU4AbRnBSb7D/ah5kZxz4L+U9RhuADlmGTooRx5rLMI9BSnU65Ibxct5DcE4cgyxOAipiYOmIL2uuk/XFeZXXpumCcObX3tKmZCZSS+a3A/Uwwy4MdBRzFhMiSYnfNgcysw7br3gRUqlrc0k4TW+gneHpI3cpyV0/BQGgQkAVfRzlXC0wEAhwllRK6f48nt8PH+Bhd8JFtS/Sq9RsDr4IIstqKPNvWl/xv+6SlaFMYEd5/qRGyU/Z0ViUZVjgecQ0REcNIq837ZSywOj5YXXI8EWtRfpk=
        file: mqtt-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.zip
        on:
          tags: true
        skip_cleanup: 'true'
        