language: c
sudo: required
dist: trusty

os:
- linux
- osx

before_install:
- wget -O paho.mqtt.c-1.3.2.tar.gz https://github.com/eclipse/paho.mqtt.c/archive/v1.3.2.tar.gz
- tar -zxf paho.mqtt.c-1.3.2.tar.gz
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update -qq && sudo apt-get install -y libssl-dev; fi
- if [ $TRAVIS_OS_NAME = osx ]; then brew install openssl && export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" && export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"; fi

before_script:
- make --directory paho.mqtt.c-1.3.2
- sudo make install --directory paho.mqtt.c-1.3.2
- export PAHO_HOME=~/paho.mqtt.c-1.3.2

script:
- make 
